2023-06-19 16:46:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Tipo de dato desconocido : "VARCHAS"
Unknown data type: "VARCHAS"; SQL statement:
CREATE TABLE USUARIO (ID INT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL,EMAIL VARCHAS (100) NOT NULL,SUELDO NUMERIC(15,2) NOT NULL) [50004-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readIfDataType1(Parser.java:6249)
	at org.h2.command.Parser.readIfDataType(Parser.java:6087)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:6069)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5948)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:9331)
	at org.h2.command.Parser.parseCreateTable(Parser.java:9271)
	at org.h2.command.Parser.parseCreate(Parser.java:6784)
	at org.h2.command.Parser.parsePrepared(Parser.java:763)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:53)
	at org.h2.command.CommandList.update(CommandList.java:66)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.example.Main.main(Main.java:30)
2023-06-19 17:10:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 17:12:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Valor Invalido "0" para el parametro "columnIndex"
Invalid value "0" for parameter "columnIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at org.example.Main.main(Main.java:72)
2023-06-19 17:12:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 17:14:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 17:14:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 17:18:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 17:19:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Valor Invalido "0" para el parametro "columnIndex"
Invalid value "0" for parameter "columnIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at org.example.Main.main(Main.java:73)
2023-06-19 17:20:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Valor Invalido "0" para el parametro "columnIndex"
Invalid value "0" for parameter "columnIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at org.example.Main.main(Main.java:73)
2023-06-19 17:30:57 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/OneDrive/Escritorio/digitalHouse/DH/backend1/bkGround/test5/pacientesEnH2/Database/my.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/OneDrive/Escritorio/digitalHouse/DH/backend1/bkGround/test5/pacientesEnH2/Database/my.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.example.Main.getConnection(Main.java:97)
	at org.example.Main.main(Main.java:37)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/OneDrive/Escritorio/digitalHouse/DH/backend1/bkGround/test5/pacientesEnH2/Database/my.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/OneDrive/Escritorio/digitalHouse/DH/backend1/bkGround/test5/pacientesEnH2/Database/my.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 19 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/OneDrive/Escritorio/digitalHouse/DH/backend1/bkGround/test5/pacientesEnH2/Database/my.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 13 more
2023-06-19 19:22:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El conjunto de resultados NO es scrollable y no puede ser reseteada. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3617)
	at org.h2.jdbc.JdbcResultSet.beforeFirst(JdbcResultSet.java:3091)
	at org.example.Main.main(Main.java:78)
2023-06-19 19:23:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El conjunto de resultados NO es scrollable y no puede ser reseteada. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3617)
	at org.h2.jdbc.JdbcResultSet.beforeFirst(JdbcResultSet.java:3091)
	at org.example.Main.main(Main.java:78)
2023-06-19 19:27:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El conjunto de resultados NO es scrollable y no puede ser reseteada. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3617)
	at org.h2.jdbc.JdbcResultSet.beforeFirst(JdbcResultSet.java:3091)
	at org.example.Main.main(Main.java:78)
2023-06-19 19:29:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El conjunto de resultados NO es scrollable y no puede ser reseteada. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3617)
	at org.h2.jdbc.JdbcResultSet.beforeFirst(JdbcResultSet.java:3091)
	at org.example.Main.main(Main.java:80)
2023-06-19 19:32:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-214]
2023-06-19 19:39:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "Email\0009" no encontrada
Column "Email\0009" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at org.example.Main.main(Main.java:77)
2023-06-19 21:33:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Este metodo no esta permitido para una sentencia preparada; en su lugar use una sentencia regular.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:303)
	at org.example.Main.main(Main.java:70)
2023-06-19 22:03:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"
Data conversion error converting "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"; SQL statement:
UPDATE USUARIO SET SUELDO=? WHERE EMAIL=? [22018-214]
2023-06-19 22:04:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"
Data conversion error converting "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"; SQL statement:
UPDATE USUARIO SET SUELDO=? WHERE EMAIL=? [22018-214]
2023-06-19 22:05:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"
Data conversion error converting "CAST('Infinity' AS DOUBLE PRECISION) (USUARIO: ""SUELDO"" NUMERIC(15, 2) NOT NULL)"; SQL statement:
UPDATE USUARIO SET SUELDO=? WHERE EMAIL=? [22018-214]
